"""Versioned known-egress-capable Python distributions.

This data set is a tripwire input, not a safety proof. A distribution absent
from this set may still be egress-capable; policy enforcement remains
deny-by-default for ``network:none`` when known egress capability is detected.

Contract changes must update ``KNOWN_EGRESS_VERSION`` and include tests or
evidence for additions/removals. Names are stored in PEP 503 canonical form:
lowercase with each run of ``-``, ``_``, or ``.`` collapsed to ``-``.
"""
from __future__ import annotations

KNOWN_EGRESS_VERSION = "2026.07.1"

KNOWN_EGRESS_DISTS = frozenset(
    {
        "aiobotocore",
        "aiodns",
        "aiohttp",
        "aiohttp-socks",
        "aiohttp-wsgi",
        "aiokafka",
        "aiomysql",
        "aiopg",
        "aioredis",
        "aiosmtplib",
        "asyncpg",
        "azure-core",
        "azure-identity",
        "azure-storage-blob",
        "boto",
        "boto3",
        "botocore",
        "cassandra-driver",
        "channels",
        "confluent-kafka",
        "couchdb",
        "databases",
        "django-channels",
        "dnspython",
        "elasticsearch",
        "fastapi",
        "flask-socketio",
        "geventhttpclient",
        "google-api-core",
        "google-api-python-client",
        "google-auth",
        "google-cloud",
        "google-cloud-bigquery",
        "google-cloud-core",
        "google-cloud-pubsub",
        "google-cloud-storage",
        "grpcio",
        "gspread",
        "h11",
        "h2",
        "httplib2",
        "httptools",
        "httpcore",
        "httpie",
        "httpx",
        "hypercorn",
        "impacket",
        "kafka-python",
        "kombu",
        "ldap3",
        "mysqlclient",
        "nats-py",
        "netaddr",
        "paramiko",
        "pika",
        "psycopg",
        "psycopg2",
        "psycopg2-binary",
        "pycurl",
        "pymemcache",
        "pymongo",
        "pymysql",
        "pynats",
        "pyopenssl",
        "pysftp",
        "python-engineio",
        "python-socketio",
        "pyzmq",
        "redis",
        "requests",
        "requests-aws4auth",
        "requests-cache",
        "requests-file",
        "requests-ftp",
        "requests-oauthlib",
        "requests-toolbelt",
        "sanic",
        "scrapy",
        "slack-sdk",
        "socketio",
        "sqlalchemy",
        "starlette",
        "telethon",
        "tornado",
        "treq",
        "twisted",
        "urllib3",
        "uvicorn",
        "websocket-client",
        "websockets",
        "werkzeug",
        "wsproto",
        "zeep",
    }
)

__all__ = ["KNOWN_EGRESS_DISTS", "KNOWN_EGRESS_VERSION"]
