"""Orchestrator build identity (offload-topology.md / PKG-1).

gx10.orchestrator_version() reads env GX10_ORCHESTRATOR_VERSION → sibling VERSION file → "unknown",
cached after first read. Pure read (no git/SHA logic in core). Surfaced in /health + at boot.
"""
from __future__ import annotations

import sys
import types
from pathlib import Path

sys.modules.setdefault("openai", types.SimpleNamespace(OpenAI=object))
_ENGINE = Path(__file__).resolve().parents[2] / "engine"
if str(_ENGINE) not in sys.path:
    sys.path.insert(0, str(_ENGINE))

import gx10  # noqa: E402
import pytest  # noqa: E402


@pytest.fixture(autouse=True)
def _reset_cache(monkeypatch):
    monkeypatch.setattr(gx10, "_ORCH_VERSION", None, raising=False)
    yield
    monkeypatch.setattr(gx10, "_ORCH_VERSION", None, raising=False)


def test_env_overrides(monkeypatch):
    monkeypatch.setenv("GX10_ORCHESTRATOR_VERSION", "abc1234")
    assert gx10.orchestrator_version() == "abc1234"


def test_cached_after_first_read(monkeypatch):
    monkeypatch.setenv("GX10_ORCHESTRATOR_VERSION", "v1")
    assert gx10.orchestrator_version() == "v1"
    monkeypatch.setenv("GX10_ORCHESTRATOR_VERSION", "v2")   # changed after first read
    assert gx10.orchestrator_version() == "v1"              # still cached


def test_unknown_when_no_env_and_no_file(monkeypatch):
    monkeypatch.delenv("GX10_ORCHESTRATOR_VERSION", raising=False)
    # No VERSION file in the dev tree (it's generated by the deploy/install stamp, gitignored).
    if (Path(gx10.__file__).resolve().parent / "VERSION").exists():
        pytest.skip("a stamped VERSION file is present in this tree")
    assert gx10.orchestrator_version() == "unknown"
