"""Test skeleton for case ``{{case_name}}`` ({{domain_title}}).

Generated by the ACK generator. Replace the placeholders with real behavioural
tests as you implement ``skills/{{case_name}}.py``.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest

_SKILL = Path(__file__).resolve().parent.parent / "skills" / "{{case_name}}.py"


def _load():
    spec = importlib.util.spec_from_file_location("_case_{{case_name}}", _SKILL)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_case_descriptor_present():
    mod = _load()
    assert mod.CASE["capability"] == "{{capability_key}}"
    assert mod.CASE["domain"] == "{{domain_name}}"
    assert mod.CASE["name"] == "{{case_name}}"


def test_run_is_a_scaffold_until_implemented():
    """Remove/replace once run() is implemented per the Case-Spec."""
    mod = _load()
    with pytest.raises(NotImplementedError):
        mod.run()
