"""Skill stub for case ``{{case_name}}`` ({{domain_title}}).

Generated by the ACK generator. This is a *procedural skill* placeholder: a
recurring multi-step operation that is *retrieved* instead of re-derived.

Self-registers via the ``CASE`` descriptor (discovered by ``skills/__init__.py``).
Capability key: ``{{capability_key}}``.
"""

from __future__ import annotations

# Discovered by the sibling ``__init__.py`` registry.
CASE: dict = {
    "name": "{{case_name}}",
    "capability": "{{capability_key}}",
    "domain": "{{domain_name}}",
    "description": "{{description}}",
}


def run(context: dict | None = None) -> dict:
    """Execute the {{case_title}} procedure.

    TODO: implement. Keep it within the case scope; route any LLM call through the
    injected chat transport (``ack.validated_emit.emit_validated``) — never the
    network directly.
    """
    # ACK-SCAFFOLD-SENTINEL — remove this line once run() is implemented. The generation-completeness
    # gate (ack.gate.gate_generated) REJECTS an item that still carries this marker (an unfilled scaffold).
    raise NotImplementedError(
        "Case '{{capability_key}}' is a scaffold — implement run() per "
        "{{case_name}}-spec.md before wiring it in."
    )
